# Generated by Django 4.0.4 on 2022-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('R', 'Rubles'), ('E', 'EURO'), ('D', 'DOLLAR')], default='R', max_length=3),
        ),
    ]
